providers:
  - airtap-sauce
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: [8..10, 12..latest] # Safari 11 fails due to https://github.com/airtap/airtap/issues/310
  - name: MicrosoftEdge
    version: -2..latest
  - name: ie
    version: 11
  - name: iphone
    version: '10.3..latest'
  - name: android
    version: '6.0..latest'
server: ./test/server/index.js
scripts:
  - "/test-polyfill.js"
browserify:
  - options:
      dedupe: false
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
